/*!
*  \file    stmproject.cpp
*  \author  Caleb Amoa Buahin <caleb.buahin@gmail.com>
*  \version 1.0.0
*  \section Description
*  This file and its associated files and libraries are free software;
*  you can redistribute it and/or modify it under the terms of the
*  Lesser GNU General Public License as published by the Free Software Foundation;
*  either version 3 of the License, or (at your option) any later version.
*  fvhmcompopnent.h its associated files is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.(see <http://www.gnu.org/licenses/> for details)
*  \date 2018
*  \pre
*  \bug
*  \todo
*  \warning
*/

#ifndef ELEMENJUNCTION_H
#define ELEMENJUNCTION_H

#include <string>
#include <set>

#include "variable.h"

class STMModel;
class HCVertex;
struct Element;

/*!
 * \brief The ElementJunction struct represents the
 */
struct ElementJunction
{

    enum JunctionType
    {
      NoElement = 0,
      SingleElement = 1,
      DoubleElement = 2,
      MultiElement = 3
    };

    /*!
     * \brief ElementJunction
     * \param numsolutes - Number of solutes
     * \param model -
     */
    ElementJunction(const std::string &id, double x, double y, double z, STMModel *model);

    /*!
     * \brief ~ElementJunction - Deletes the ElementJunction and its associated data.
     */
    ~ElementJunction();

    /*!
     * \brief id unique identifier for this junction
     */
    std::string id;

    /*!
     * \brief index
     */
    int index;

    /*!
     * \brief x location
     */
    double x;

    /*!
     * \brief y location
     */
    double y;

    /*!
     * \brief z location
     */
    double z;

    /*!
     * \brief continuityIndex
     */
    int heatContinuityIndex = -1;

    /*!
     * \brief soluteContinuityIndexes
     */
    int *soluteContinuityIndexes;

    /*!
     * \brief numSolutes
     */
    int numSolutes;

    /*!
     * \brief xSectionArea
     */
    double xSectionArea;

    /*!
     * \brief temperature
     */
    Variable temperature;

    /*!
     * \brief prevTemperature
     */
    Variable prevTemperature;

    /*!
     * \brief soluteConcs
     */
    Variable *soluteConcs;

    /*!
     * \brief prevSoluteConcs
     */
    Variable *prevSoluteConcs;

    /*!
     * \brief lateralFluxes Q * T. Applicable only if node is not junction. i.e. Headwater / Outlet. m^3.C/s
     */
    Variable externalHeatFlux;

    /*!
     * \brief lateralSoluteFluxes
     */
    Variable *externalSoluteFluxes;

    /*!
     * \brief incomingElements
     */
    std::set<Element*> incomingElements;

    /*!
     * \brief outgoingElements
     */
    std::set<Element*> outgoingElements;

    /*!
     * \brief longDispersion
     */
    double longDispersion;

    double longDispersion_length;

    /*!
     * \brief junctionType
     */
    JunctionType junctionType;

    /*!
     * \brief model
     */
    STMModel *model;

    /*!
     * \brief initializeSolutes
     * \param numSolutes
     */
    void initializeSolutes(int numSolutes);

    /*!
     * \brief interpLongDispersion
     */
    void interpLongDispersion();

    /*!
     * \brief interpTemp
     */
    void interpTemp();

    /*!
     * \brief interpXSectionArea
     */
    void interpXSectionArea();

    /*!
     * \brief interpSoluteConcs
     */
    void interpSoluteConcs(int soluteIndex);

    /*!
     * \brief computeDTDt - Computes the time derivative of temperature at this junction if it is DoubleElement or MultiElement junction using the dual
     * control volume derived using Yoshioka, H. and K. Unami, 2013 (A Cell-Vertex Finite Volume Scheme for Solute Transport Equations in
     * Open Channel Networks. Probabilistic Engineering Mechanics 31:30–38.).
     * Dispersion across the junction is assumed to be negligible.
     * \param dt - The timestep over which to compute the gradient.
     * \return Returns the temperature time derivative.
     */
    double computeDTDt(double dt);

    /*!
     * \brief computeDSoluteDt - Computes the solute time derivative.
     * \param dt - The timestep over which to compute the solute gradient.
     * \param soluteIndex - The index for the solute.
     * \return Returns the value of the solute time derivative.
     */
    double computeDSoluteDt(double dt, int soluteIndex);

    /*!
     * \brief computeDTDt - Computes the time derivative of temperature based on data generated by the ODE solver.
     * \param dt - The timestep over which to compute the solute gradient.
     * \param T - The temperature array for all elements.
     * \return
     */
    double computeDTDt(double dt, double T[]);

    /*!
     * \brief computeDSoluteDt
     * \param dt
     * \param S
     * \param soluteIndex
     * \return
     */
    double computeDSoluteDt(double dt, double S[], int soluteIndex);

    /*!
     * \brief copyVariablesToPrev
     */
    void copyVariablesToPrev();

};


#endif // ELEMENJUNCTION_H
